spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&allowPublicKeyRetrieval=true&useSSL=false

    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

data:
  rest:
    base-path: /api
    default-page-size: 10
    max-page-size: 10